### ISSUE TITLE
Multiple reminder text, only one italicized

### ISSUE THREAD

**Issue by MrTeferi** [chilli-axe/mtg-photoshop-automation#34] opened 2022-01-28 17:35 UTC
Someone brought to my attention that cards with two separate instances of reminder text will only render the first text in italics but not the second, I've included an example image. Trying to find other cards to replicate this with but I don't think there are many cards with this situation
![Timeless Dragon](https://user-images.githubusercontent.com/92750180/151594674-fd181106-26d2-4855-b79b-e8dc759f0897.png)

**Comment by MrTeferi** [comment] 2022-01-28 18:29
Apparently its not solely due to there being two separate reminder text and related to some other issue, because Ardent Plea renders correctly:
![Ardent Plea](https://user-images.githubusercontent.com/92750180/151601840-8b7ea1d0-99cd-40ed-a83c-c81269c1c4e6.png)

Any ideas?

**Comment by ndepaola** [comment] 2022-01-29 01:39
this was occurring due to the reminder text for eternalise having 2 instances of `{W}`, and only the first instance was being replaced with `ow` (the font representation of that symbol) when identifying the start/end indices of the italics string within the body of text. Root cause was `string.replace` only replacing the first instance of the specified substring, not all instances. it can be reproduced with other cards that have multiple instances of the same symbol within italics symbols - e.g. most eternalise cards. fixed in https://github.com/chilli-axe/mtg-photoshop-automation/commit/bd5d4095a172f8c5dbcbf50e6b5e1833bbebe806 by using regex to replace all instances.

**Closed by ndepaola** 2022-01-29 01:39 UTC
